Backup: 2026-01-02 18:31:13

diff --git a/DSA/build b/DSA/build
--- a/DSA/build
+++ b/DSA/build
@@ -8,8 +8,8 @@ CLR_CYAN='\033[0;36m'
 CLR_BOLD='\033[1m'
 
 if [ -z "$1" ]; then
-	echo -e "${CLR_BOLD}${CLR_RED}ERROR:${CLR_RESET} File must be provided as argument"
-	exit 1
+    echo -e "${CLR_BOLD}${CLR_RED}ERROR:${CLR_RESET} File must be provided as argument"
+    exit 1
 fi
 
 filename="$1"
@@ -21,80 +21,89 @@ to_run=false
 flags="-g -Wall -Wextra"
 
 case "$command" in
-clean)
-	echo -e "${CLR_YELLOW}Removing ${target}${CLR_RESET}"
-	rm -f "$target"
-	exit 0
-	;;
-run)
-	if [ -z "$2" ]; then
-		echo -e "${CLR_BOLD}${CLR_RED}ERROR:${CLR_RESET} 'run' command requires a source file."
-		exit 1
-	fi
-	filename=$2
-	to_run=true
-	;;
+    clean)
+        echo -e "${CLR_YELLOW}Removing ${target}${CLR_RESET}"
+        rm -f "$target"
+        exit 0
+        ;;
+    help)
+        echo "Try again..."
+        exit 0
+        ;;
+    run)
+        if [ -z "$2" ]; then
+            echo -e "${CLR_BOLD}${CLR_RED}ERROR:${CLR_RESET} 'run' command requires a source file."
+            exit 1
+        fi
+        filename=$2
+        to_run=true
+        ;;
 esac
 
 extension="${filename##*.}"
 
 case "$extension" in
-"cpp" | "cxx" | "cc")
-	filetype="cpp"
-	compiler="g++"
-	echo -e "${CLR_CYAN}C++ Source File Recognized${CLR_RESET}"
-	;;
-"c")
-	filetype="c"
-	compiler="gcc"
-	echo -e "${CLR_CYAN}C Source File Recognized${CLR_RESET}"
-	;;
-*)
-    echo -en "${CLR_BOLD}${CLR_RED}ERROR: ${CLR_RESET}"
-	if [ "$extension" == "$filename" ]; then
-		echo "File has no extension"
-	else
-		echo "Invalid File Type (extension: .$extension)"
-        echo "       Only C and C++ files are supported"
-	fi
-	exit 1
-	;;
+    "cpp" | "cxx" | "cc")
+        filetype="cpp"
+        compiler="g++"
+        echo -e "${CLR_CYAN}C++ Source File Recognized${CLR_RESET}"
+        ;;
+    "c")
+        filetype="c"
+        compiler="gcc"
+        echo -e "${CLR_CYAN}C Source File Recognized${CLR_RESET}"
+        ;;
+    *)
+        echo -en "${CLR_BOLD}${CLR_RED}ERROR: ${CLR_RESET}"
+        if [ "$extension" == "$filename" ]; then
+            echo "File has no extension"
+        else
+            echo "Invalid File Type (extension: .$extension)"
+            echo "       Only C and C++ files are supported"
+        fi
+        exit 1
+        ;;
 esac
 
 util=""
-if grep ${utilname} ${filename} 1>/dev/null; then
+if grep ${utilname} "${filename}" 1>/dev/null; then
     echo -e "${CLR_YELLOW}Using utils...${CLR_RESET}"
-	util+=" ${utildir}/${utilname}.${filetype}"
+    util+=" ${utildir}/${utilname}.${filetype}"
 fi
 
-if grep "queue.h" ${filename} 1>/dev/null; then
+if grep "queue.h" "${filename}" 1>/dev/null; then
     echo -e "${CLR_YELLOW}Using queue...${CLR_RESET}"
-	util+=" generics/queue.c"
+    util+=" generics/queue.c"
 fi
 
-if grep "stack.h" ${filename} 1>/dev/null; then
+if grep "stack.h" "${filename}" 1>/dev/null; then
     echo -e "${CLR_YELLOW}Using stack...${CLR_RESET}"
-	util+=" generics/stack.c"
+    util+=" generics/stack.c"
 fi
 
-if grep "bt.h" ${filename} 1>/dev/null; then
+if grep "bt.h" "${filename}" 1>/dev/null; then
     echo -e "${CLR_YELLOW}Using binarytree...${CLR_RESET}"
-	util+=" Tree/binarytree.c"
+    util+=" Tree/binarytree.c"
 fi
 
-if grep "hash_map.h" ${filename} 1>/dev/null; then
+if grep "bst.h" "${filename}" 1>/dev/null; then
+    echo -e "${CLR_YELLOW}Using binarysearchtree...${CLR_RESET}"
+    util+=" Tree/binarySearchTree.c Tree/binarytree.c"
+fi
+
+if grep "hash_map.h" "${filename}" 1>/dev/null; then
     echo -e "${CLR_YELLOW}Using hashmap...${CLR_RESET}"
-	util+=" Hash/hash_map.c"
+    util+=" Hash/hash_map.c"
 fi
 
 echo -e "${CLR_YELLOW}Compiling...${CLR_RESET}"
 
-if ${compiler} -o ${target} ${filename} ${util} ${flags}; then
-	echo -e "${CLR_GREEN}Compiled: ${target}${CLR_RESET}"
-	if $to_run; then
-		echo -e "${CLR_YELLOW}Running the program...${CLR_RESET}"
-		./${target}
-	fi
+if ${compiler} ${flags} -o ${target} "${filename}" ${util}; then
+    echo -e "${CLR_GREEN}Compiled: ${target}${CLR_RESET}"
+    if $to_run; then
+        echo -e "${CLR_YELLOW}Running the program...${CLR_RESET}"
+        ./${target}
+    fi
 else
-	echo -e "${CLR_BOLD}${CLR_RED}Compilation failed!!!${CLR_RESET}"
+    echo -e "${CLR_BOLD}${CLR_RED}Compilation failed!!!${CLR_RESET}"
 fi
